version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./:/app
    command: sh -c "cd /app && npm run dev"
    ports:
      - "3000:3000"
